- name: Install useful application
  apt:
    name:
      - htop
      - tree
      - mc
      - net-tools
    state: latest
    update_cache: true

- name: Enable UFW
  community.general.ufw:
    state: enabled

# TODO Try to change task for changing user to ansible on group_vars