- name: Get docker ver
  command: docker --version
  register: docker_check
  changed_when: false

- name: Show docker ver
  debug:
    msg: "Docker ver: {{ docker_check.stdout }}"

- name: Setup docker daemon
  service:
    name: docker
    enabled: yes
    state: started

- name: Create custom docker network
  community.docker.docker_network:
    name: "{{ net_name }}"
    driver: bridge
    ipam_config:
      - subnet: "{{ docker_network }}.0/24"
        gateway: "{{ docker_network }}.1"
    state: present

