- name: Setup proxy conf file
  template:
    src: "nginx/{{ proxy_app_conf }}"
    dest: "{{ proxy_app_conf_dir }}/{{ proxy_app_conf }}"
    state: directory
    mode: '644'
    recurse: yes
  notify: Setup TLS

